sudo: required
services:
  - docker

install:
  - ":" # do nothing
script:
  - ping localhost -c 60 & # Prevent killing
  - docker build -t tsuzu/webrtc .
after_success:
      - if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push tsuzu/webrtc;
        fi
