sudo: required
services:
  - docker

install:
  - ":" # do nothing
script:
  - docker build -t tsuzu/WebRTC .
after_success:
      - if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push tsuzu/WebRTC;
        fi
